### ISSUE TITLE
Using https://github.com/cloud-bulldozer/e2e-benchmarking without having the right to.

### ISSUE THREAD

**Issue by sandrobonazzola** [redhat-chaos/managed-services-deploy#8]
This project is leveraging https://github.com/cloud-bulldozer/e2e-benchmarking which is not licensed and as such it cannot be used.
Opened https://github.com/cloud-bulldozer/e2e-benchmarking/issues/459 to address this but in the meanwhile this project is not usable as well.

**Comment by chaitanyaenr** [comment]
Fixed by https://github.com/cloud-bulldozer/e2e-benchmarking/pull/460.
